<?php

namespace DoctrineORMModule\Proxy\__CG__\RequirementsManager\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Artifact extends \RequirementsManager\Entity\Artifact implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'id', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'user_id', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'blocked', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'title', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'artifact_status_id', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'artifact_priority_id', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'module_id', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'created_on', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'description', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'updated_on', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'soft_delete', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'delete_reason', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'version', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'artifact_comments', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'desc', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'artifact_review', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'artifact_text', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'ancestors', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'descendants');
        }

        return array('__isInitialized__', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'id', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'user_id', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'blocked', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'title', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'artifact_status_id', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'artifact_priority_id', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'module_id', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'created_on', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'description', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'updated_on', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'soft_delete', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'delete_reason', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'version', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'artifact_comments', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'desc', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'artifact_review', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'artifact_text', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'ancestors', '' . "\0" . 'RequirementsManager\\Entity\\Artifact' . "\0" . 'descendants');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Artifact $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', array());

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserId($user_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserId', array($user_id));

        return parent::setUserId($user_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getBlocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlocked', array());

        return parent::getBlocked();
    }

    /**
     * {@inheritDoc}
     */
    public function setBlocked($blocked)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBlocked', array($blocked));

        return parent::setBlocked($blocked);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtifactStatusId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtifactStatusId', array());

        return parent::getArtifactStatusId();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtifactStatusId($artifact_status_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtifactStatusId', array($artifact_status_id));

        return parent::setArtifactStatusId($artifact_status_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtifactPriorityId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtifactPriorityId', array());

        return parent::getArtifactPriorityId();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtifactPriorityId($artifact_priority_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtifactPriorityId', array($artifact_priority_id));

        return parent::setArtifactPriorityId($artifact_priority_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getModuleId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModuleId', array());

        return parent::getModuleId();
    }

    /**
     * {@inheritDoc}
     */
    public function setModuleId($module_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModuleId', array($module_id));

        return parent::setModuleId($module_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedOn', array());

        return parent::getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedOn($created_on)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedOn', array($created_on));

        return parent::setCreatedOn($created_on);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedOn', array());

        return parent::getUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedOn($updated_on)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedOn', array($updated_on));

        return parent::setUpdatedOn($updated_on);
    }

    /**
     * {@inheritDoc}
     */
    public function getSoftDelete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoftDelete', array());

        return parent::getSoftDelete();
    }

    /**
     * {@inheritDoc}
     */
    public function setSoftDelete($soft_delete)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSoftDelete', array($soft_delete));

        return parent::setSoftDelete($soft_delete);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeleteReason()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeleteReason', array());

        return parent::getDeleteReason();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleteReason($delete_reason)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleteReason', array($delete_reason));

        return parent::setDeleteReason($delete_reason);
    }

    /**
     * {@inheritDoc}
     */
    public function getVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersion', array());

        return parent::getVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersion($version)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersion', array($version));

        return parent::setVersion($version);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtifactComments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtifactComments', array());

        return parent::getArtifactComments();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtifactComments($artifact_comments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtifactComments', array($artifact_comments));

        return parent::setArtifactComments($artifact_comments);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtifactReview()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtifactReview', array());

        return parent::getArtifactReview();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtifactReview($artifact_review)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtifactReview', array($artifact_review));

        return parent::setArtifactReview($artifact_review);
    }

    /**
     * {@inheritDoc}
     */
    public function getAncestors()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAncestors', array());

        return parent::getAncestors();
    }

    /**
     * {@inheritDoc}
     */
    public function setAncestors($ancestors)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAncestors', array($ancestors));

        return parent::setAncestors($ancestors);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAncestors($ancestors)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAncestors', array($ancestors));

        return parent::removeAncestors($ancestors);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescendants()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescendants', array());

        return parent::getDescendants();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescendants($descendants)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescendants', array($descendants));

        return parent::setDescendants($descendants);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDescendants($descendants)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDescendants', array($descendants));

        return parent::removeDescendants($descendants);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtifactText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtifactText', array());

        return parent::getArtifactText();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtifactText($artifact_text)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtifactText', array($artifact_text));

        return parent::setArtifactText($artifact_text);
    }

    /**
     * {@inheritDoc}
     */
    public function getDesc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDesc', array());

        return parent::getDesc();
    }

    /**
     * {@inheritDoc}
     */
    public function setDesc($desc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDesc', array($desc));

        return parent::setDesc($desc);
    }

}
