<?php

namespace DoctrineORMModule\Proxy\__CG__\RequirementsManager\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \RequirementsManager\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'RequirementsManager\\Entity\\User' . "\0" . 'id', '' . "\0" . 'RequirementsManager\\Entity\\User' . "\0" . 'username', '' . "\0" . 'RequirementsManager\\Entity\\User' . "\0" . 'password', '' . "\0" . 'RequirementsManager\\Entity\\User' . "\0" . 'role_id', '' . "\0" . 'RequirementsManager\\Entity\\User' . "\0" . 'first_name', '' . "\0" . 'RequirementsManager\\Entity\\User' . "\0" . 'last_name', '' . "\0" . 'RequirementsManager\\Entity\\User' . "\0" . 'email', '' . "\0" . 'RequirementsManager\\Entity\\User' . "\0" . 'created_on', '' . "\0" . 'RequirementsManager\\Entity\\User' . "\0" . 'project', '' . "\0" . 'RequirementsManager\\Entity\\User' . "\0" . 'artifact_comments', '' . "\0" . 'RequirementsManager\\Entity\\User' . "\0" . 'artifact_review', '' . "\0" . 'RequirementsManager\\Entity\\User' . "\0" . 'soft_delete');
        }

        return array('__isInitialized__', '' . "\0" . 'RequirementsManager\\Entity\\User' . "\0" . 'id', '' . "\0" . 'RequirementsManager\\Entity\\User' . "\0" . 'username', '' . "\0" . 'RequirementsManager\\Entity\\User' . "\0" . 'password', '' . "\0" . 'RequirementsManager\\Entity\\User' . "\0" . 'role_id', '' . "\0" . 'RequirementsManager\\Entity\\User' . "\0" . 'first_name', '' . "\0" . 'RequirementsManager\\Entity\\User' . "\0" . 'last_name', '' . "\0" . 'RequirementsManager\\Entity\\User' . "\0" . 'email', '' . "\0" . 'RequirementsManager\\Entity\\User' . "\0" . 'created_on', '' . "\0" . 'RequirementsManager\\Entity\\User' . "\0" . 'project', '' . "\0" . 'RequirementsManager\\Entity\\User' . "\0" . 'artifact_comments', '' . "\0" . 'RequirementsManager\\Entity\\User' . "\0" . 'artifact_review', '' . "\0" . 'RequirementsManager\\Entity\\User' . "\0" . 'soft_delete');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoleId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoleId', array());

        return parent::getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoleId($role_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoleId', array($role_id));

        return parent::setRoleId($role_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', array());

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName($first_name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', array($first_name));

        return parent::setFirstName($first_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', array());

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName($last_name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', array($last_name));

        return parent::setLastName($last_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedOn', array());

        return parent::getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedOn($created_on)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedOn', array($created_on));

        return parent::setCreatedOn($created_on);
    }

    /**
     * {@inheritDoc}
     */
    public function getProject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProject', array());

        return parent::getProject();
    }

    /**
     * {@inheritDoc}
     */
    public function setProject($project)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProject', array($project));

        return parent::setProject($project);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtifactComments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtifactComments', array());

        return parent::getArtifactComments();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtifactComments($artifact_comments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtifactComments', array($artifact_comments));

        return parent::setArtifactComments($artifact_comments);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtifactReview()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtifactReview', array());

        return parent::getArtifactReview();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtifactReview($artifact_review)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtifactReview', array($artifact_review));

        return parent::setArtifactReview($artifact_review);
    }

    /**
     * {@inheritDoc}
     */
    public function getSoftDelete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoftDelete', array());

        return parent::getSoftDelete();
    }

    /**
     * {@inheritDoc}
     */
    public function setSoftDelete($soft_delete)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSoftDelete', array($soft_delete));

        return parent::setSoftDelete($soft_delete);
    }

}
